[versions]
agp = "8.12.3"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
uwb = "1.0.0-alpha10"
playServicesNearby = "19.3.0"
kotlin = "2.2.0"
coreKtx = "1.12.0"
guava = "31.1-android"
kotlinCoroutines = "1.7.3"
truth = "1.1.5"
androidxTestCore = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTestRules = "1.5.0"
coreKtxVersion = "1.17.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
uwb = { group = "androidx.core.uwb", name = "uwb", version.ref = "uwb" }
play-services-nearby = { group = "com.google.android.gms", name = "play-services-nearby", version.ref = "playServicesNearby" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
guava-android = { group = "com.google.guava", name = "guava", version.ref = "guava" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinCoroutines" }
test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

